Code/core/urls.py
from core import views
from django.urls import path
from core import views
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    admin_user,
    order_list,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    aboutUs,
    admin_item,
    user_list,
    
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('all-products/', views.products, name='products'),
    path('home/<str:category>/', HomeView.as_view(), name='home-category'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('admin-item/<slug>/', admin_item, name='admin-item'),
    path('admin-user/<userProfile>/', admin_user, name='admin-user'),
    path('user-list/', user_list, name='user-list'),
    path('order-list/', order_list, name='order-list'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('opinions/' ,views.opinions,name='opinions'),
    path('opinions/<int:opinion_id>/', views.opinions_details,name="opinionDetails"),
    path('opinions/create/', views.create_opinion,name="opinionCreate"),
    path('opinions/<int:opinion_id>/addResponse/', views.createResponse,name="responseCreate"),
    path('profile/',views.profile),
    path('about-us/' ,aboutUs,name='about-us'),
    path('condiciones/' ,views.condiciones,name='condiciones'),
    path('politica/' ,views.politica,name='politica'),
]

Code/core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
        email = models.EmailField(unique=True)
        USERNAME_FIELD = 'email'
        REQUIRED_FIELDS = ['username']

CATEGORY_CHOICES = (
    ('MP', 'Maquinaria Pesada'),
    ('MS', 'Maquinaria Semipesada'),
    ('ML', 'Maquinaria Ligera')
)

FABRICANTE_CHOICES = (
    ('CAT', 'Caterpillar'),
    ('KMT', 'Komatsu'),
    ('X', 'XCMG'),
    ('JD', 'John Deere'),
    ('S', 'Sany'),

)

DISPONIBILITY_CHOICES = (
    ('D', 'Disponible'),
    ('ND', 'No disponible')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

STATE_CHOICES = (
    ('CF', 'Confirmado'),
    ('EV', 'Enviado'),
    ('EP', 'En preparacion'),
    ('RB', 'Recibido'),
    ('AN', 'Anulado'),
    
)








class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)
    DNI = models.CharField(max_length=9, blank=True, null=True)
    telefono = models.CharField(max_length=9, blank=True, null=True)
    
    primary_address = models.ForeignKey(
        'Address', related_name='primary_address', on_delete=models.SET_NULL, blank=True, null=True)
    
    card_number = models.BigIntegerField(blank=True, null=True)
    card_expiry = models.PositiveIntegerField(blank=True, null=True)
    card_expiry_month = models.PositiveSmallIntegerField(blank=True, null=True)
    card_expiry_year = models.PositiveIntegerField(blank=True, null=True)
    card_cvc = models.PositiveSmallIntegerField(blank=True, null=True)
    has_card_details = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    fabricante = models.CharField(choices=FABRICANTE_CHOICES, max_length=3)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    disponibility = models.CharField(choices=DISPONIBILITY_CHOICES, max_length=2,null=True)
    selected = models.BooleanField(default = False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })
    
    def get_admin_item_panel(self):
        return reverse("core:admin-item", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_final_price(self):
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    statement = models.CharField(choices=STATE_CHOICES, max_length=2,null=True, default='Confirmado')
    payment_type = models.BooleanField(default=False)
    shipping = models.BooleanField(default=True, blank=True, null=True)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
      
        return total


    def is_shipping_cost(self):
        return not(self.shipping) or self.get_total() > 50
    
    def get_final_price(self):
        if self.is_shipping_cost():
            return self.get_total()
        else:
            return self.get_total() + 3.99    


class Address(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_addresses')
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Response(models.Model):
    description = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    opinion = models.ForeignKey('Opinion', related_name='opinion', on_delete=models.CASCADE, blank=True, null=True)                         

class Opinion(models.Model):
    title = models.CharField(max_length = 20)
    description = models.CharField(max_length = 100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    
    
    def get_absolute_url(self):
        return '/opinions/%s' %(self.id)

def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

Code/templates/about-us.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<div class="container">
    <div class="row">
        <div class="col-md-6 d-flex align-items-center">
            <div>
                <h1 class="text-center">Acerca de Nosotros</h1>
                <p>Somos una empresa especializada en el alquiler y venta de maquinaria de construcción, comprometida con proporcionar equipos de primera calidad para tus proyectos.</p>
                <p>Destacamos por ofrecer un servicio personalizado y profesional, manteniendo un trato cercano y familiar con nuestros clientes. Nuestra prioridad es brindar soluciones eficientes a tus necesidades en el ámbito de la construcción.</p>
                <p>Además, hemos implementado un servicio online que facilita tu experiencia con nosotros. Ahora puedes explorar nuestro catálogo, realizar consultas y gestionar tus pedidos desde la comodidad de tu hogar u oficina.</p>
                <p>Confía en nosotros para obtener la maquinaria de construcción que requieres, respaldada por años de experiencia y un compromiso inquebrantable con la satisfacción de nuestros clientes. Juntos, construyamos el éxito de tus proyectos.</p>
                <p>Con más de 30 años de experiencia en la industria de la construcción, Jesus Valderrama fundó nuestra empresa con la visión de proporcionar soluciones integrales y equipos de calidad para proyectos de construcción de todo tipo. Su dedicación y pasión por la construcción han sido la fuerza impulsora detrás de nuestro éxito continuo.</p>
            </div>
        </div>
        <div class="col-md-6 text-center">
            <img src="{% static 'img/jesus.png' %}" alt="Foto de Jesus Valderrama" class="img-fluid h-100">
            <p class="font-weight-bold text-uppercase text-center">Jesus Torres Valderrama - Fundador</p>

            
        </div>
    </div>
</div>



{% endblock content %}

Code/templates/admin_item.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}

<style>
    /* Personalizar estilos del formulario */
    .form-group label {
        color: white;  /* Color blanco para las etiquetas */
    }

    .form-group input,
    .form-group select,
    .form-group textarea {
        color: black;  /* Ajusta el color del texto de entrada según tus preferencias */
    }
</style>

<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">
    <div class="row">
      <div class="col-md-6">
        <h1 class="font-weight-bold text-warning" style="text-shadow: 2px 2px 2px black;">{{ item.title|title }}</h1>
      </div>
    </div>
    <!--Grid row-->
    <div class="row wow fadeIn">
      <!--Grid column-->
      <div class="col-md-6 mb-4">
        <img src="{{ item.image.url }}" class="img-fluid" alt="">
      </div>
      <!--Grid column-->
      <!--Grid column-->
      <div class="col-md-6 mb-4">
        <!--Content-->
        <form method="post" enctype="multipart/form-data" class="mt-4">
          {% csrf_token %}
          <div class="form-group">
            {{ form.as_p }}
          </div>
          <button type="submit">Guardar cambios</button>
        </form>
        
        <!--Content-->
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
    <hr>
  </div>
</main>

{% endblock content %}

Code/templates/condiciones.html
{% extends "base.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Términos y Condiciones - JesseRentals</title>
    <style>
        

        .container {
            max-width: 800px;
            margin: 0 auto;
        }

        #title {
            text-align: center;
            color: #ff9900;  /* Amarillo CAT */
            font-size: 28px;
            font-weight: bold;
        }

        #content {
            text-align: justify;
            line-height: 1.6;
        }

        #prohibited-uses {
            margin-top: 15px;
        }

        .prohibited-use {
            list-style-type: none;
            padding: 0;
        }

        .prohibited-use li::before {
            content: "\2022";
            color: #ff9900;  /* Amarillo CAT */
            font-weight: bold;
            display: inline-block;
            width: 1em;
            margin-left: -1em;
        }
    </style>
</head>
<body>

<div class="container">
    <h1 id="title">Términos y Condiciones - JesseRentals</h1>
    <div id="content">
        <p>Gracias por elegir JesseRentals, su socio confiable en alquiler y venta de maquinaria de construcción. Por favor, lea atentamente los siguientes términos y condiciones antes de utilizar nuestro sitio web:</p>

        <p><strong>Uso Personal:</strong> La información proporcionada en este sitio web está destinada únicamente para uso personal. No está permitido utilizarla con fines comerciales sin autorización previa de JesseRentals.</p>

        <div id="prohibited-uses">
            <p><strong>Usos Prohibidos:</strong> No se permite el uso de este sitio web de manera contraria a la ley. Esto incluye, pero no se limita a:</p>
            <ul class="prohibited-use">
                <li>Causar engaño a los demás.</li>
                <li>Atentar contra la moralidad pública.</li>
                <li>Violar derechos de propiedad intelectual o derechos similares.</li>
                <li>Cargar contenido que contenga virus u otros programas dañinos.</li>
                <li>Transmitir, almacenar o cargar hipervínculos o contenidos sobre los que el usuario no tenga derecho, especialmente cuando dichos enlaces o contenidos sean ilegales y violen la ley de protección de datos personales.</li>
                <li>Distribuir publicidad o correos electrónicos no solicitados (spam).</li>
            </ul>
        </div>

        <p>Gracias por su cooperación. Si tiene alguna pregunta o necesita más información, no dude en ponerse en contacto con nosotros.</p>
    </div>
</div>

</body>
</html>


{% endblock content %}

Code/templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn black">

  <hr class="my-4">

  <div class="container">
    <div class="row">
  
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto m-0 text-center text-white">
        <h5>Sobre nosotros
        </h5>
        <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">

        <ul class="list-unstyled">

          <li><a href="/about-us/">Quienes somos y que hacemos</a></li>

        </ul>

      </div>


      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto m-0 text-center text-white">
        <h5>Información Relevante
        </h5>
        <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">

        <ul class="list-unstyled">

          <li><a href="/condiciones/">ir a condiciones de uso</a></li>
          <li><a href="/politica/">ir a política de devoluciones</a></li>
          <li><a class="nav-link" href="/opinions">Opiniones</a></li>

        </ul>

      </div>

      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto m-0 text-center text-white">
        <h5>Centro de reclamaciones y sugerencias</h5>
        <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">

        <ul class="list-unstyled">

          <li><a href="/opinions/">ir al centro de Reclamaciones y sugerencias</a></li>

        </ul>
      </div>

      <div class="m-0 text-center text-white">
        <h5>Contacto</h5>
        <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
        <ul class="list-unstyled">
          <li><a href="mailto:jesserentalsamjr@gmail.com" style="text-decoration:none;"><i
                class="fa fa-home mr-2"></i>JesseRentals correo</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!--Copyright-->
  <div class="footer-copyright py-3">

    © 2023 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> JesseRentals </a>
  </div>
  <!--/.Copyright-->

</footer>

Code/templates/home.html
{% extends "base.html" %}

{% block content %}

<style>
  /* Estilo para la card Caterpillar */
  .caterpillar-card {
    border: 1px solid #ddd;
    /* Borde de la card */
    border-radius: 10px;
    /* Bordes redondeados */
    overflow: hidden;
    /* Para ocultar cualquier desbordamiento de contenido */
    transition: transform 0.3s;
    /* Efecto de transición en hover */
  }

  .caterpillar-card:hover {
    transform: scale(1.05);
    /* Efecto de escala en hover */
  }

  /* Estilo para la imagen en la card */
  .caterpillar-card .card-img-top {
    border-bottom: 1px solid #ddd;
    /* Borde inferior de la imagen */
  }

  /* Estilo para el botón de "Añadir al carrito" */
  .caterpillar-card .add-to-cart-btn {
    background-color: #ffc107;
    /* Amarillo Caterpillar */
    color: #000;
    /* Texto en negro */
    border: 1px solid #ffc107;
    /* Borde del botón */
  }

  .caterpillar-card .add-to-cart-btn:hover {
    background-color: #ffca2b;
    /* Amarillo ligeramente más claro en hover */
    color: #000;
    /* Texto en negro en hover */
    border: 1px solid #ffca2b;
    /* Borde del botón en hover */
  }

  /* Estilo para el precio */
  .caterpillar-card .font-weight-bold {
    color: #000;
    /* Texto del precio en negro */
  }
</style>

<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark black lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categorías:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'core:home' %}">Todas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:home-category' category='MP'%}">Maquinaria Pesada</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:home-category' category='MS'%}">Maquinaria Semipesada</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:home-category' category='ML'%}">Maquinaria Ligera</a>
          </li>

          <!-- Otros enlaces para las demás categorías -->
        </ul>
        <!-- Links -->

        <form class="form-inline" method="GET">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Buscar producto" aria-label="Buscar producto"
              name="search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <div class="row wow fadeIn">

        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card black">

            <div class="view overlay">
              <img src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="dark-grey-text">
                <h5>{{ item.get_category_display }}</h5>
        
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="white-text">{{ item.title }}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">Nuevo</span>
                    <span class="badge badge-pill badge-warning" style="color: #000 !important;">{{ item.get_fabricante_display }}</span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold white-text">
                <strong>$

                  {{ item.price }}

                </strong>
              </h4>

              
              {% if user.is_authenticated and user.is_staff %}
              <a href="{{ item.get_admin_item_panel }}" class="edit-btn btn btn-info btn-md my-0 p text-light">
                Editar
                <i class="fas fa-edit ml-1"></i>
              </a>
              {% else %}
              {% if item.get_disponibility_display == "Disponible" %}
              <a href="{{ item.get_add_to_cart_url }}" class="add-to-cart-btn btn btn-warning btn-md my-0 p text-dark">
                Añadir al carrito
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
              
              {% else %}
              <a href="">
                <span class="badge red mr-1">{{ item.get_disponibility_display }}</span>
              </a>
              {% endif %}
              {% endif %}



            </div>

          </div>

        </div>
        {% endfor %}
      </div>

    </section>
    <!--Section: Products v.3-->

    {% if is_paginated %} <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

  </div>
</main>


{% endblock content %}

Code/templates/invoice.html
{% extends "base.html" %}

{% block content %}

<main>
    <div class="container wow fadeIn">
        <h2 class="my-5 h2 text-center">Factura del pedido</h2>

        <div class="row">
            <div class="col-md-8 mb-4">
                <h3>Información del cliente</h3>
                <p>Email: {{ order.user.email }}</p>
                <p>DNI: {{ order.user.DNI }}</p>
                <p>Teléfono: {{ order.user.telefono }}</p>

                <h3>Información de envío</h3>
                {% if order.shipping_option == 'D' %}
                <p>Dirección de envío: {{ order.user.shipping_address.street_address }}</p>
                <p>País: {{ order.user.shipping_address.country }}</p>
                <p>Código postal: {{ order.user.shipping_address.zip }}</p>
                {% else %}
                <p>Opción de envío: {{ order.user.shipping_option }}</p>
                {% endif %}

                <h3>Información de pago</h3>
                {% if order.payment_option == 'T' %}
                <p>Número de tarjeta: {{ order.user.card_number }}</p>
                <p>Fecha de caducidad: {{ order.user.card_expiry_month }}/{{ order.user.card_expiry_year }}</p>
                <p>CVC: {{ order.user.card_cvc }}</p>
                {% else %}
                <p>Opción de pago: {{ order.user.payment_option }}</p>
                {% endif %}
            </div>
        </div>

        <hr class="mb-4">

        <h3>Detalles del pedido</h3>
        {% include "order_snippet.html" %}

    </div>
</main>

{% endblock content %}

Code/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<main>
    <div class="container">

        <div class="table-responsive text-nowrap">
            <h2 class="text-white">Resumen del pedido</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" class="text-white">#</th>
                        <th scope="col" class="text-white">Producto</th>
                        <th scope="col" class="text-white">Precio</th>
                        <th scope="col" class="text-white">Cantidad</th>
                        <th scope="col" class="text-white">Total Precio Productos</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row" class="text-white">{{ forloop.counter }}</th>
                        <td class="text-white">{{ order_item.item.title }}</td>
                        <td class="text-white">{{ order_item.item.price }}</td>
                        <td class="text-white">
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i
                                    class="fas fa-minus mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i
                                    class="fas fa-plus ml-2"></i></a>
                        </td>
                        <td class="text-white">
                            {% if order_item.item.discount_price %}
                            ${{ order_item.get_total_discount_item_price }}
                            <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                            {% else %}
                            ${{ order_item.get_total_item_price }}
                            {% endif %}
                            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                <i class="fas fa-trash float-right"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='5' class="text-white">Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-primary float-right text-white' href='/'>Continuar comprando</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if object.coupon %}
                    <tr>
                        <td colspan="4" class="text-white"><b>Coupon</b></td>
                        <td class="text-white"><b>-${{ object.coupon.amount }}</b></td>
                    </tr>
                    {% endif %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="4" class="text-white"><b>Total Pedido</b></td>
                        <td class="text-white"><b>${{ object.get_total }}</b></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-warning float-right ml-2 text-white' href='/checkout/'>Proceder al pago</a>
                            <a class='btn btn-primary float-right text-white' href='/'>Continuar comprando</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>

        </div>

    </div>
</main>

{% endblock content %}